language: node_js
sudo: false
group: travis_latest

stages:
  - &testAndLint Test and lint

cached_stage: &cachedStage
  cache:
    directories:
      - node_modules
      - example/node_modules
  before_cache:
    - rm -rf ./node_modules/.cache
    - rm -rf example/node_modules/.cache
    - rm -rf example/node_modules/express-decorated-router

test_stage: &testStageBase
  stage: *testAndLint
  <<: *cachedStage
  before_script: export EXAMPLE_SKIP_PARENT_NPM_INSTALL=1
  script:
    - npm run test -- --forbid-only --forbid-pending
    - bash -c "cd example && npm install"
    - bash -c "cd example && npm test -- --forbid-only --forbid-pending"
  after_success: cat ./coverage/lcov.info | coveralls

jobs:
  include:
    - stage: *testAndLint
      <<: *cachedStage
      node_js: &latestTested 9
      env:
        - LINT=1
      before_install:
        - cp package.json package.json.bak
        - node ./build/filter-lint-depedencies.js
      before_script: mv package.json.bak package.json -f
      script: npm run lint
    - <<: *testStageBase
      node_js: 9
    - <<: *testStageBase
      node_js: 8
    - <<: *testStageBase
      node_js: 6
    - <<: *testStageBase
      node_js: "6.0"
