language: node_js
sudo: false

stages:
- Test
- name: Release
  if: branch = master AND type = push AND (NOT tag IS present)

env:
  global:
  - EXAMPLE_SKIP_PARENT_NPM_INSTALL=1

cache:
  directories:
  - node_modules
  - example/node_modules

before_cache:
- rm -rf ./node_modules/.cache
- rm -rf example/node_modules/.cache
- rm -rf example/node_modules/express-decorated-router

before_install:
- node build/sync-dep-versions.js
- npm install -g greenkeeper-lockfile
- &prepKey if [[ $GH_TOKEN ]]; then ./prepare-gpg-key.sh; fi;
- greenkeeper-lockfile-update
install: npm install

script:
- npm run test -- --forbid-only --forbid-pending --retries 3 --timeout 20000
- bash -c "cd example && npm install"
- bash -c "cd example && npm test -- --forbid-only --forbid-pending --retries 3 --timeout 20000"

after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
after_success: cat ./coverage/lcov.info | coveralls

jobs:
  include:
  - stage: Test
    node_js: stable
    script:
    - npm run lint
    - npm run test -- --forbid-only --forbid-pending --retries 3 --timeout 20000
    - bash -c "cd example && npm install"
    - bash -c "cd example && npm test -- --forbid-only --forbid-pending --retries 3 --timeout 20000"
    - semantic-release --dry-run
  - stage: Test
    node_js: lts/dubnium
  - stage: Test
    node_js: lts/carbon
  - stage: Release
    node_js: stable
    before_install: *prepKey
    env:
    - CI_RELEASE=1
    cache:
      directories:
      - node_modules
    before_cache: rm -rf ./node_modules/.cache
    before_script: npm run build:release
    script: semantic-release
    after_success: []
    after_script: []
