language: node_js
sudo: false
group: travis_latest

node_js:
  - stable
  - lts/carbon
  - lts/boron

stages:
  - name: &releaseStage Release
    if: tag IS present

env:
  global:
    - EXAMPLE_SKIP_PARENT_NPM_INSTALL=1

cache:
  directories:
    - node_modules
    - example/node_modules

before_cache:
  - rm -rf ./node_modules/.cache
  - rm -rf example/node_modules/.cache
  - rm -rf example/node_modules/express-decorated-router

before_install:
  - npm install -g greenkeeper-lockfile
  - greenkeeper-lockfile-update
install: npm install

after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
after_success: cat ./coverage/lcov.info | coveralls

script:
  - npm run lint
  - npm run test -- --forbid-only --forbid-pending --retries 3 --timeout 20000
  - bash -c "cd example && npm install"
  - bash -c "cd example && npm test -- --forbid-only --forbid-pending --retries 3 --timeout 20000"

jobs:
  include:
    - stage: *releaseStage
      node_js: stable
      before_install: false
      env:
        - CI_RELEASE=1
      cache:
        directories:
          - node_modules
      before_cache: rm -rf ./node_modules/.cache
      script: node ./build/replace-ver.js
      before_script: npm run build:release
      after_success: false
      after_script: false
      deploy:
        - provider: npm
          on:
            tags: true
          skip_cleanup: true
          email: a.molcanovas@gmail.com
          api_key:
            secure: "AKcIcgmZKvOsGx77Tlpt1A/kRv7pJPso1/J0GDKQY8mB+R7/t+DTMv97uHGBf1ahGsTQTnRJIivfisCBDhPHDqXBQO7SaiUO7KB6LhqRXAeXaTYULYIenXluXKfRpqPHpCJSJzuGr3ly9+VGChBgTe9U0dNnDkCPAU4ulRp9euL1NL8MG9SWUZKxSkT0FddF0paWBB6MOPmI0w8WgUNeXlcJTmvzZmAtQeQ/Qb2pN8XkUf1FdI831D3J2Xlq1V+T8m2QHVJcWsTikHppse2yMLHfYMCCwF426nRb/WRaY+tgf0x40dldd3GzP40LAhyfG8HQE7fixDZhdLSTGifdMMSoCjK1itkfD6W3GR5rVEgqO9mAer/QC9a2GPw9Bxm62ZqXfnpqKlRn5VG6q0vgKap0tRG6FOsMhSp77FaZKNMmbV1ulIaV5nWBd5oYLwfsTm8ZcVu4q7zE1WL2xBLqZwdHJ0L2Ng5qvepUrKxP1MqLqJHUGAvPDu/9IF53ZBJil6YFDtQA9UzPGjXW32iNNjirP1XVM/2HytwfhLVJ0Chtu7y75UHA9KZ+9AoJbb0f2gaZ9fPQCPiwMlJ1s80Oey+O1byn2bL3TuKAgLPUakugCG2ZOlG4ltLza/UJEfbZ/lun4sn21bigt3QAaBVIwHLjal8j7reoOA7SkkbLbog="
