language: node_js
sudo: false
group: travis_latest

stages:
  - &testAndLint Test and lint

cached_stage: &cachedStage
  cache:
    directories:
      - node_modules
  before_cache: rm -rf ./node_modules/.cache

test_stage: &testStageBase
  stage: *testAndLint
  <<: *cachedStage
  script: npm run test -- --forbid-only --forbid-pending
  before_script: npm run typecheck
  after_success: cat ./coverage/lcov.info | coveralls

jobs:
  include:
    - stage: *testAndLint
      <<: *cachedStage
      node_js: &latestTested 9
      env:
        - LINT=1
      before_install:
        - cp package.json package.json.bak
        - node ./build/filter-lint-depedencies.js
      before_script: mv package.json.bak package.json -f
      script: npm run lint
    - <<: *testStageBase
      node_js: 9
    - <<: *testStageBase
      node_js: 8
    - <<: *testStageBase
      node_js: 6
    - <<: *testStageBase
      node_js: "6.0"
